const ACTION_TYPES = {
  MESSAGE_TEXT: 'MESSAGE_TEXT',
  MESSAGE_IMG: 'MESSAGE_IMG',
  CONVERSATION_CREATE: 'CONVERSATION_CREATE',
  CONVERSATION_UPDATE: 'CONVERSATION_UPDATE',
  CONVERSATION_DELETE: 'CONVERSATION_DELETE',
  CONVERSATION_TEMP_CREATE: 'CONVERSATION_TEMP_CREATE',
  CONVERSATION_TEMP_UPDATE: 'CONVERSATION_TEMP_UPDATE',
  CONVERSATION_TEMP_DELETE: 'CONVERSATION_TEMP_DELETE',
  CONVERSATION_NOTIFICATION: 'CONVERSATION_NOTIFICATION',
  CONVERSATION_CHANGE_CURRENT: 'CONVERSATION_CHANGE_CURRENT',
  SEARCH_USER_IN_CONVERSATIONS: 'SEARCH_USER_IN_CONVERSATIONS',
};

export default ACTION_TYPES;
