const ACTION_TYPES = {
  MESSAGE_TEXT: 'MESSAGE_TEXT',
  MESSAGE_IMG: 'MESSAGE_IMG',
  CONVERSATION_JOIN: 'CONVERSATION_JOIN',
  CONVERSATION_LEAVE: 'CONVERSATION_LEAVE',
  CONVERSATION_CHANGE_CURRENT: 'CONVERSATION_CHANGE_CURRENT',
};

export default ACTION_TYPES;
