const NOTIFICATION_TYPES = {
  MEMBER_JOIN: 'JOIN',
  MEMBER_LEAVE: 'LEAVE',
  CONVERSATION_CREATED: 'CONVERSATION_CREATED',
  IMAGE: 'IMAGE',
  MESSAGE: 'MESSAGE',
};

export default NOTIFICATION_TYPES;
